configMapGenerator:
- files:
  - application.yml
  name: 82273986-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/82273986
  newTag: "202411180713"
- name: cepgstapacr.azurecr.io/82273986
  newTag: "202411181428"
